### ISSUE TITLE
specify R script(s)

### ISSUE THREAD

**Issue by ggrothendieck** [eddelbuettel/pkgkitten#16]
An argument that allows one to specify the names(s) of R script(s) to get the functions from would be useful for converting a script to a package.

```
library(pkgKitten)
library(devtools)

kitten("myPackage", author = "me", script = "myScript.R")
setwd("myPackage")
build()
install()

library(myPackage)
```

**Comment by ggrothendieck** [comment]
Could you just add a dot dot dot argument to kitten and then pass it to package.skeleton?

**Comment by eddelbuettel** [comment]
In theory, yes. In practice I seem to be doing something moderately complicated there (possibly inherited from `Rcpp.package.skeleton()`) and it is not immediatly obvious how to get the dots in there.  On the other hand, I could probably just add `code_files()` too.  But it is not really an itch I am having so not sure if/when I get to this.

**Comment by ggrothendieck** [comment]
Seems to defeat the purpose of the package though since now someone has to understand the internal structure of packages.
