### ISSUE TITLE
Argument to avoid generating hello* files

### ISSUE THREAD

**Issue by ggrothendieck** [eddelbuettel/pkgkitten#17]
When writing a script based on `kitten` to generate a package one typically wants to delete the hello* files that it generates and that involves extra steps.  Would be desirable to have an argument that avoids generating them.
```
kitten(hello = FALSE)
```

**Comment by eddelbuettel** [comment]
I am torn. While I like it (and just had to teach a user to remove them) those actually come from `package.skeleton()`.  But then again you offer an _option_ rather than enforcing it.  So let me move the needle from torn to in favour :)

When you send a PR please also add a line to ChangeLog.  Date, name, email; separated by two spaces.

**Comment by eddelbuettel** [comment]
Actually, I may have misremembered.  When we run `kitten()` in default mode it adds a `hello.R` to have an file:

```sh

edd@rob:/tmp/kitten$ kitten.r foo
Creating directories ...
Creating DESCRIPTION ...
Creating NAMESPACE ...
Creating Read-and-delete-me ...
Saving functions and data ...
Making help files ...
Done.
Further steps are described in './foo/Read-and-delete-me'.

Adding pkgKitten overrides.
 >> added .gitignore file
 >> added .Rbuildignore file
Deleted 'Read-and-delete-me'.
Done.

Consider reading the documentation for all the packaging details.
A good start is the 'Writing R Extensions' manual.

And run 'R CMD check'. Run it frequently. And think of those kittens.

edd@rob:/tmp/kitten$ ls foo/
DESCRIPTION  man  NAMESPACE  R
edd@rob:/tmp/kitten$ tree foo
foo
├── DESCRIPTION
├── man
│   ├── foo-package.Rd
│   └── hello.Rd
├── NAMESPACE
└── R
    └── hello.R

2 directories, 5 files
edd@rob:/tmp/kitten$ 
```

If we remove that we have no R file.  Would that really be good?   

The code could easily be conditioned on a new flag:

https://github.com/eddelbuettel/pkgkitten/blob/77c949ca135d10496858a525e24094521942f603/R/pkgKitten.R#L120-L126

But do we really want that?  Maybe in power-user mode?

**Comment by eddelbuettel** [comment]
Closing as stale / lack of follow-up.  Feel free to re-open if you have fresh energy.
