### ISSUE TITLE
bug in kitten when called with a non-default path

### ISSUE THREAD

**Issue by paulhodor** [eddelbuettel/pkgkitten#19]
Hi Dirk,

I discovered your package while learning about test-driven development with tinytest. Very helpful, thanks.

While experimenting with the kitten() function, I came across a small bug. When the function is called with an explicit path, the step  that creates the tinytest files fails. For example:
```
kitten("cucu", path="~/tmp")
```
I submitted a pull request containing a fix. In the pull request I also corrected a typo in the function help. Looks like you have some sort of pipeline for generating documentation, which you will have to run to propagate the typo fix.

Best,
Paul

**Comment by eddelbuettel** [comment]
Closed by https://github.com/eddelbuettel/pkgkitten/pull/18 -- thanks again!
