### ISSUE TITLE
test for hello function

### ISSUE THREAD

**Issue by paulhodor** [eddelbuettel/pkgkitten#20]
Hi Dirk, one other thing: The tinytest support adds a completely unhelpful test. I was thinking about replacing it with a test for the actual hello() function. Would you be interested in pulling that in?
Best,
Paul

**Comment by eddelbuettel** [comment]
So you want to add a test for `hello()` concatenating the string and printing to stdout?  Could do, but I also like the greater simplicity of the existing test.

Maybe split it in the middle, and add an `adder()` function for which a simple numeric check can be added (as I find testing `stdout` to be one abstraction level higher and I'd rather not complicate things to keep the lowest possible barrier to entry).

Also please see the open question to you in #18.

**Comment by paulhodor** [comment]
Adding another simple function will address the abstraction issue with stdout, but I worry about the proliferation of files. It is nice to keep things minimal. How about keeping the simple test that does nothing and adding the hello test that uses stdout?

**Comment by eddelbuettel** [comment]
Closed by #18 -- thanks again!
